#!/usr/bin/env sh

set -e

if [ ! -f "/etc/sockd.conf" ]; then
    # Configure SOCKS port
    # shellcheck disable=SC2016
    envsubst '$SOCKS_PORT $SOCKS_INTERFACE_INTERNAL $SOCKS_INTERFACE_EXTERNAL' </etc/sockd_env.conf >/etc/sockd.conf
fi

exec sockd "$@"
