#!/usr/bin/env sh

set -e

if [ "$DANTE_CONF" = "/etc/sockd.conf" ]; then
    # Configure SOCKS port
    # shellcheck disable=SC2016
    envsubst '$SOCKS_PORT' </etc/sockd.conf >/tmp/sockd.conf
    mv /tmp/sockd.conf /etc/sockd.conf
fi

exec sockd "$@"
